//
//  Rect.h
//  MNN
//
//  Modified by jiangxiaotang on 2018/09/19.
//  Copyright © 2018, Alibaba Group Holding Limited
//

/*
 * Copyright 2006 The Android Open Source Project
 *
 * Use of this source code is governed by a BSD-style license that can be
 * found in the LICENSE file.
 */

/**
 * @file Rect.h
 * @brief MNN 矩形类
 * 
 * 该文件定义了用于计算机视觉（CV）的矩形结构 Rect 和点结构 Point。
 * 主要功能包括：
 * - 矩形创建（空矩形、指定宽高、指定边界等）
 * - 矩形操作（偏移、内缩、外扩）
 * - 矩形查询（空检查、包含检查、相交检查）
 * - 矩形合并（并集操作）
 * 
 * 设计特点：
 * - 基于 Skia 图形库的 Rect 实现
 * - 使用 float 类型存储坐标，支持子像素精度
 * - 支持空矩形概念（left >= right 或 top >= bottom）
 * - 提供丰富的工厂方法和操作函数
 */

/* Generated by tools/bookmaker from include/core/Rect.h and docs/SkRect_Reference.bmh
   on 2018-07-13 08:15:11. Additional documentation and examples can be found at:
   https://skia.org/user/api/SkRect_Reference

   You may edit either file directly. Structural changes to public interfaces require
   editing both files. After editing docs/SkRect_Reference.bmh, run:
       bookmaker -b docs -i include/core/Rect.h -p
   to create an updated version of this file.
 */

#ifndef MNN_Rect_DEFINED
#define MNN_Rect_DEFINED

#include <math.h>
#include <algorithm>
#include <utility>
#include <MNN/MNNDefine.h>

namespace MNN {
namespace CV {

/**
 * @brief 二维点结构
 * 
 * 表示平面上的一个点，使用 float 类型存储 x 和 y 坐标。
 * 主要用于矩形操作中的位置表示。
 */
struct Point {
    float fX;  //!< x 坐标
    float fY;  //!< y 坐标

    /**
     * @brief 设置点的坐标
     * @param x x 坐标值
     * @param y y 坐标值
     */
    void set(float x, float y) {
        fX = x;
        fY = y;
    }
};

/**
 * @brief 矩形结构
 * 
 * Rect 包含四个 float 坐标，描述矩形的上下左右边界。
 * 可以通过外边界或位置、宽度、高度来创建。
 * 如果 right <= left 或 bottom <= top，则矩形被认为是空的。
 * 
 * 坐标系统：
 * - 原点 (0, 0) 在左上角
 * - X 轴向右增加
 * - Y 轴向下增加
 */
/** \struct Rect
    Rect holds four float coordinates describing the upper and
    lower bounds of a rectangle. Rect may be created from outer bounds or
    from position, width, and height. Rect describes an area; if its right
    is less than or equal to its left, or if its bottom is less than or equal to
    its top, it is considered empty.
*/
struct MNN_PUBLIC Rect {
    float fLeft;   //!< 左边界（较小的 x 值）
    float fTop;    //!< 上边界（较小的 y 值）
    float fRight;  //!< 右边界（较大的 x 值）
    float fBottom; //!< 下边界（较大的 y 值）

    /**
     * @brief 创建空矩形
     * @return 边界为 (0, 0, 0, 0) 的矩形
     * 
     * 空矩形的特征是 left >= right 或 top >= bottom。
     * 注意：全零只是一种便利，不代表特殊的空矩形。
     */
    /** Returns constructed Rect set to (0, 0, 0, 0).
        Many other rectangles are empty; if left is equal to or greater than right,
        or if top is equal to or greater than bottom. Setting all members to zero
        is a convenience, but does not designate a special empty rectangle.

        @return  bounds (0, 0, 0, 0)
    */
    static constexpr Rect MakeEmpty() {
        return Rect{0, 0, 0, 0};
    }

#ifdef SK_SUPPORT_LEGACY_RECTMAKELARGEST
    /** Deprecated.
     */
    static Rect MakeLargest() {
        return {SK_ScalarMin, SK_ScalarMin, SK_ScalarMax, SK_ScalarMax};
    }
#endif

    /**
     * @brief 创建指定宽高的矩形
     * @param w 宽度
     * @param h 高度
     * @return 边界为 (0, 0, w, h) 的矩形
     * 
     * 不验证输入，w 或 h 可能为负数。
     * 传入整数可能产生编译器警告，因为 Rect 不能精确表示 32 位整数。
     */
    /** Returns constructed Rect set to float values (0, 0, w, h). Does not
        validate input; w or h may be negative.

        Passing integer values may generate a compiler warning since Rect cannot
        represent 32-bit integers exactly. Use SkIRect for an exact integer rectangle.

        @param w  float width of constructed Rect
        @param h  float height of constructed Rect
        @return   bounds (0, 0, w, h)
    */
    static constexpr Rect MakeWH(float w, float h) {
        return Rect{0, 0, w, h};
    }

    /**
     * @brief 使用整数宽高创建矩形
     * @param w 整数宽度
     * @param h 整数高度
     * @return 边界为 (0, 0, w, h) 的矩形
     * 
     * 用于避免整数输入可能丢失精度的编译器警告。
     */
    /** Returns constructed Rect set to integer values (0, 0, w, h). Does not validate
        input; w or h may be negative.

        Use to avoid a compiler warning that input may lose precision when stored.
        Use SkIRect for an exact integer rectangle.

        @param w  integer width of constructed Rect
        @param h  integer height of constructed Rect
        @return   bounds (0, 0, w, h)
    */
    static Rect MakeIWH(int w, int h) {
        Rect r;
        r.set(0, 0, (float)(w), (float)(h));
        return r;
    }

    /**
     * @brief 使用四边边界创建矩形
     * @param l 左边界
     * @param t 上边界
     * @param r 右边界
     * @param b 下边界
     * @return 边界为 (l, t, r, b) 的矩形
     * 
     * 不排序输入，left 可能大于 right，top 可能大于 bottom。
     */
    /** Returns constructed Rect set to (l, t, r, b). Does not sort input; Rect may
        result in fLeft greater than fRight, or fTop greater than fBottom.

        @param l  float stored in fLeft
        @param t  float stored in fTop
        @param r  float stored in fRight
        @param b  float stored in fBottom
        @return   bounds (l, t, r, b)
    */
    static constexpr Rect MakeLTRB(float l, float t, float r, float b) {
        return Rect{l, t, r, b};
    }

    /**
     * @brief 使用位置和宽高创建矩形
     * @param x 左上角 x 坐标
     * @param y 左上角 y 坐标
     * @param w 宽度
     * @param h 高度
     * @return 边界为 (x, y, x+w, y+h) 的矩形
     * 
     * 不验证输入，w 或 h 可能为负数。
     */
    /** Returns constructed Rect set to (x, y, x + w, y + h). Does not validate input;
        w or h may be negative.

        @param x  stored in fLeft
        @param y  stored in fTop
        @param w  added to x and stored in fRight
        @param h  added to y and stored in fBottom
        @return   bounds at (x, y) with width w and height h
    */
    static constexpr Rect MakeXYWH(float x, float y, float w, float h) {
        return Rect{x, y, x + w, y + h};
    }

    /**
     * @brief 检查矩形是否为空
     * @return 如果 width <= 0 或 height <= 0 返回 true
     * 
     * 空矩形的特征是 left >= right 或 top >= bottom。
     * 如果任何值为 NaN，也会返回 true。
     */
    /** Returns true if fLeft is equal to or greater than fRight, or if fTop is equal
        to or greater than fBottom. Call sort() to reverse rectangles with negative
        width() or height().

        @return  true if width() or height() are zero or negative
    */
    bool isEmpty() const {
        // We write it as the NOT of a non-empty rect, so we will return true if any values
        // are NaN.
        return !(fLeft < fRight && fTop < fBottom);
    }

    /**
     * @brief 检查矩形是否已排序
     * @return 如果 left <= right 且 top <= bottom 返回 true
     * 
     * 已排序的矩形具有非负的宽度和高度。
     */
    /** Returns true if fLeft is equal to or less than fRight, or if fTop is equal
        to or less than fBottom. Call sort() to reverse rectangles with negative
        width() or height().

        @return  true if width() or height() are zero or positive
    */
    bool isSorted() const {
        return fLeft <= fRight && fTop <= fBottom;
    }

    /**
     * @brief 获取左边界
     * @return fLeft 的值
     * 
     * 假设矩形已排序。如果矩形可能无效，先调用 isEmpty() 检查。
     */
    /** Returns left edge of Rect, if sorted. Call isSorted() to see if Rect is valid.
        Call sort() to reverse fLeft and fRight if needed.

        @return  fLeft
    */
    float x() const {
        return fLeft;
    }

    /**
     * @brief 获取上边界
     * @return fTop 的值
     * 
     * 假设矩形已排序。如果矩形可能无效，先调用 isEmpty() 检查。
     */
    /** Returns top edge of Rect, if sorted. Call isEmpty() to see if Rect may be invalid,
        and sort() to reverse fTop and fBottom if needed.

        @return  fTop
    */
    float y() const {
        return fTop;
    }

    /**
     * @brief 获取左边界
     * @return fLeft 的值
     */
    /** Returns left edge of Rect, if sorted. Call isSorted() to see if Rect is valid.
        Call sort() to reverse fLeft and fRight if needed.

        @return  fLeft
    */
    float left() const {
        return fLeft;
    }

    /**
     * @brief 获取上边界
     * @return fTop 的值
     */
    /** Returns top edge of Rect, if sorted. Call isEmpty() to see if Rect may be invalid,
        and sort() to reverse fTop and fBottom if needed.

        @return  fTop
    */
    float top() const {
        return fTop;
    }

    /**
     * @brief 获取右边界
     * @return fRight 的值
     */
    /** Returns right edge of Rect, if sorted. Call isSorted() to see if Rect is valid.
        Call sort() to reverse fLeft and fRight if needed.

        @return  fRight
    */
    float right() const {
        return fRight;
    }

    /**
     * @brief 获取下边界
     * @return fBottom 的值
     */
    /** Returns bottom edge of Rect, if sorted. Call isEmpty() to see if Rect may be invalid,
        and sort() to reverse fTop and fBottom if needed.

        @return  fBottom
    */
    float bottom() const {
        return fBottom;
    }

    /**
     * @brief 获取宽度
     * @return fRight - fLeft
     * 
     * 不检查矩形是否已排序，结果可能为负数或无穷大。
     */
    /** Returns span on the x-axis. This does not check if Rect is sorted, or if
        result fits in 32-bit float; result may be negative or infinity.

        @return  fRight minus fLeft
    */
    float width() const {
        return fRight - fLeft;
    }

    /**
     * @brief 获取高度
     * @return fBottom - fTop
     * 
     * 不检查矩形是否已排序，结果可能为负数或无穷大。
     */
    /** Returns span on the y-axis. This does not check if Rect is sorted, or if
        result fits in 32-bit float; result may be negative or infinity.

        @return  fBottom minus fTop
    */
    float height() const {
        return fBottom - fTop;
    }

    /**
     * @brief 获取中心点 x 坐标
     * @return (left + right) / 2
     * 
     * 使用 0.5 * left + 0.5 * right 避免溢出。
     */
    /** Returns average of left edge and right edge. Result does not change if Rect
        is sorted. Result may overflow to infinity if Rect is far from the origin.

        @return  midpoint in x
    */
    float centerX() const {
        // don't use floatHalf(fLeft + fBottom) as that might overflow before the 0.5
        return 0.5f * (fLeft) + 0.5f * (fRight);
    }

    /**
     * @brief 获取中心点 y 坐标
     * @return (top + bottom) / 2
     * 
     * 使用 0.5 * top + 0.5 * bottom 避免溢出。
     */
    /** Returns average of top edge and bottom edge. Result does not change if Rect
        is sorted.

        @return  midpoint in y
    */
    float centerY() const {
        // don't use floatHalf(fTop + fBottom) as that might overflow before the 0.5
        return 0.5f * (fTop) + 0.5f * (fBottom);
    }

    /**
     * @brief 设置矩形为空
     * 
     * 将矩形设置为 (0, 0, 0, 0)。
     * 全零只是一种便利，不代表特殊的空矩形。
     */
    /** Sets Rect to (0, 0, 0, 0).

        Many other rectangles are empty; if left is equal to or greater than right,
        or if top is equal to or greater than bottom. Setting all members to zero
        is a convenience, but does not designate a special empty rectangle.
    */
    void setEmpty() {
        *this = MakeEmpty();
    }

    /**
     * @brief 设置矩形边界
     * @param left 左边界
     * @param top 上边界
     * @param right 右边界
     * @param bottom 下边界
     * 
     * 不排序输入，left 可能大于 right，top 可能大于 bottom。
     */
    /** Sets Rect to (left, top, right, bottom).
        left and right are not sorted; left is not necessarily less than right.
        top and bottom are not sorted; top is not necessarily less than bottom.

        @param left    stored in fLeft
        @param top     stored in fTop
        @param right   stored in fRight
        @param bottom  stored in fBottom
    */
    void set(float left, float top, float right, float bottom) {
        fLeft   = left;
        fTop    = top;
        fRight  = right;
        fBottom = bottom;
    }

    /**
     * @brief 设置矩形边界（与 set 相同）
     * @param left 左边界
     * @param top 上边界
     * @param right 右边界
     * @param bottom 下边界
     */
    /** Sets Rect to (left, top, right, bottom).
        left and right are not sorted; left is not necessarily less than right.
        top and bottom are not sorted; top is not necessarily less than bottom.

        @param left    stored in fLeft
        @param top     stored in fTop
        @param right   stored in fRight
        @param bottom  stored in fBottom
    */
    void setLTRB(float left, float top, float right, float bottom) {
        this->set(left, top, right, bottom);
    }

    /**
     * @brief 使用整数设置矩形边界
     * @param left 整数左边界
     * @param top 整数上边界
     * @param right 整数右边界
     * @param bottom 整数下边界
     * 
     * 所有参数从整数提升为 float。
     */
    /** Sets Rect to (left, top, right, bottom).
        All parameters are promoted from integer to scalar.
        left and right are not sorted; left is not necessarily less than right.
        top and bottom are not sorted; top is not necessarily less than bottom.

        @param left    promoted to float and stored in fLeft
        @param top     promoted to float and stored in fTop
        @param right   promoted to float and stored in fRight
        @param bottom  promoted to float and stored in fBottom
    */
    void iset(int left, int top, int right, int bottom) {
        fLeft   = (float)(left);
        fTop    = (float)(top);
        fRight  = (float)(right);
        fBottom = (float)(bottom);
    }

    /**
     * @brief 使用整数宽高设置矩形
     * @param width 整数宽度
     * @param height 整数高度
     * 
     * 将矩形设置为 (0, 0, width, height)。
     * 大值可能丢失精度。
     */
    /** Sets Rect to (0, 0, width, height).
        width and height may be zero or negative. width and height are promoted from
        integer to float, large values may lose precision.

        @param width   promoted to float and stored in fRight
        @param height  promoted to float and stored in fBottom
    */
    void isetWH(int width, int height) {
        fLeft = fTop = 0;
        fRight       = (float)(width);
        fBottom      = (float)(height);
    }

    /**
     * @brief 使用位置和宽高设置矩形
     * @param x 左上角 x 坐标
     * @param y 左上角 y 坐标
     * @param width 宽度
     * @param height 高度
     * 
     * 将矩形设置为 (x, y, x+width, y+height)。
     */
    /** Sets Rect to (x, y, x + width, y + height). Does not validate input;
        width or height may be negative.

        @param x       stored in fLeft
        @param y       stored in fTop
        @param width   added to x and stored in fRight
        @param height  added to y and stored in fBottom
    */
    void setXYWH(float x, float y, float width, float height) {
        fLeft   = x;
        fTop    = y;
        fRight  = x + width;
        fBottom = y + height;
    }

    /**
     * @brief 使用宽高设置矩形
     * @param width 宽度
     * @param height 高度
     * 
     * 将矩形设置为 (0, 0, width, height)。
     */
    /** Sets Rect to (0, 0, width, height). Does not validate input;
        width or height may be negative.

        @param width   stored in fRight
        @param height  stored in fBottom
    */
    void setWH(float width, float height) {
        fLeft   = 0;
        fTop    = 0;
        fRight  = width;
        fBottom = height;
    }

    /**
     * @brief 创建偏移后的矩形
     * @param dx x 方向偏移量
     * @param dy y 方向偏移量
     * @return 偏移后的新矩形
     * 
     * dx 为负向左移动，为正向右移动。
     * dy 为负向上移动，为正向下移动。
     */
    /** Returns Rect offset by (dx, dy).

        If dx is negative, Rect returned is moved to the left.
        If dx is positive, Rect returned is moved to the right.
        If dy is negative, Rect returned is moved upward.
        If dy is positive, Rect returned is moved downward.

        @param dx  added to fLeft and fRight
        @param dy  added to fTop and fBottom
        @return    Rect offset on axes, with original width and height
    */
    Rect makeOffset(float dx, float dy) const {
        return MakeLTRB(fLeft + dx, fTop + dy, fRight + dx, fBottom + dy);
    }

    /**
     * @brief 创建内缩后的矩形
     * @param dx x 方向内缩量
     * @param dy y 方向内缩量
     * @return 内缩后的新矩形
     * 
     * dx 为正使矩形变窄，为负使矩形变宽。
     * dy 为正使矩形变短，为负使矩形变高。
     */
    /** Returns Rect, inset by (dx, dy).

        If dx is negative, Rect returned is wider.
        If dx is positive, Rect returned is narrower.
        If dy is negative, Rect returned is taller.
        If dy is positive, Rect returned is shorter.

        @param dx  added to fLeft and subtracted from fRight
        @param dy  added to fTop and subtracted from fBottom
        @return    Rect inset symmetrically left and right, top and bottom
    */
    Rect makeInset(float dx, float dy) const {
        return MakeLTRB(fLeft + dx, fTop + dy, fRight - dx, fBottom - dy);
    }

    /**
     * @brief 创建外扩后的矩形
     * @param dx x 方向外扩量
     * @param dy y 方向外扩量
     * @return 外扩后的新矩形
     * 
     * dx 为正使矩形变宽，为负使矩形变窄。
     * dy 为正使矩形变高，为负使矩形变短。
     */
    /** Returns Rect, outset by (dx, dy).

        If dx is negative, Rect returned is narrower.
        If dx is positive, Rect returned is wider.
        If dy is negative, Rect returned is shorter.
        If dy is positive, Rect returned is taller.

        @param dx  subtracted to fLeft and added from fRight
        @param dy  subtracted to fTop and added from fBottom
        @return    Rect outset symmetrically left and right, top and bottom
    */
    Rect makeOutset(float dx, float dy) const {
        return MakeLTRB(fLeft - dx, fTop - dy, fRight + dx, fBottom + dy);
    }

    /**
     * @brief 偏移矩形
     * @param dx x 方向偏移量
     * @param dy y 方向偏移量
     * 
     * 直接修改当前矩形的位置。
     */
    /** Offsets Rect by adding dx to fLeft, fRight; and by adding dy to fTop, fBottom.

        If dx is negative, moves Rect to the left.
        If dx is positive, moves Rect to the right.
        If dy is negative, moves Rect upward.
        If dy is positive, moves Rect downward.

        @param dx  offset added to fLeft and fRight
        @param dy  offset added to fTop and fBottom
    */
    void offset(float dx, float dy) {
        fLeft += dx;
        fTop += dy;
        fRight += dx;
        fBottom += dy;
    }

    /**
     * @brief 将矩形偏移到指定位置
     * @param newX 新的左边界
     * @param newY 新的上边界
     * 
     * 保持宽度和高度不变，只改变位置。
     */
    /** Offsets Rect so that fLeft equals newX, and fTop equals newY. width and height
        are unchanged.

        @param newX  stored in fLeft, preserving width()
        @param newY  stored in fTop, preserving height()
    */
    void offsetTo(float newX, float newY) {
        fRight += newX - fLeft;
        fBottom += newY - fTop;
        fLeft = newX;
        fTop  = newY;
    }

    /**
     * @brief 内缩矩形
     * @param dx x 方向内缩量
     * @param dy y 方向内缩量
     * 
     * 直接修改当前矩形。
     */
    /** Insets Rect by (dx, dy).

        If dx is positive, makes Rect narrower.
        If dx is negative, makes Rect wider.
        If dy is positive, makes Rect shorter.
        If dy is negative, makes Rect taller.

        @param dx  added to fLeft and subtracted from fRight
        @param dy  added to fTop and subtracted from fBottom
    */
    void inset(float dx, float dy) {
        fLeft += dx;
        fTop += dy;
        fRight -= dx;
        fBottom -= dy;
    }

    /**
     * @brief 外扩矩形
     * @param dx x 方向外扩量
     * @param dy y 方向外扩量
     * 
     * 直接修改当前矩形。
     */
    /** Outsets Rect by (dx, dy).

        If dx is positive, makes Rect wider.
        If dx is negative, makes Rect narrower.
        If dy is positive, makes Rect taller.
        If dy is negative, makes Rect shorter.

        @param dx  subtracted to fLeft and added from fRight
        @param dy  subtracted to fTop and added from fBottom
    */
    void outset(float dx, float dy) {
        this->inset(-dx, -dy);
    }

private:
    /**
     * @brief 检查两个矩形是否相交（内部实现）
     * @param al 第一个矩形的左边界
     * @param at 第一个矩形的上边界
     * @param ar 第一个矩形的右边界
     * @param ab 第一个矩形的下边界
     * @param bl 第二个矩形的左边界
     * @param bt 第二个矩形的上边界
     * @param br 第二个矩形的右边界
     * @param bb 第二个矩形的下边界
     * @return 如果相交返回 true
     */
    static bool Intersects(float al, float at, float ar, float ab, float bl, float bt, float br, float bb) {
        float L = std::max(al, bl);
        float R = std::min(ar, br);
        float T = std::max(at, bt);
        float B = std::min(ab, bb);
        return L < R && T < B;
    }

public:
    /**
     * @brief 检查矩形是否与指定边界相交
     * @param left 左边界
     * @param top 上边界
     * @param right 右边界
     * @param bottom 下边界
     * @return 如果相交返回 true
     */
    /** Constructs Rect to intersect from (left, top, right, bottom). Does not sort
        construction.

        Returns true if Rect intersects construction.
        Returns false if either construction or Rect is empty, or do not intersect.

        @param left    x-axis minimum of constructed Rect
        @param top     y-axis minimum of constructed Rect
        @param right   x-axis maximum of constructed Rect
        @param bottom  y-axis maximum of constructed Rect
        @return        true if construction and Rect have area in common
    */
    bool intersects(float left, float top, float right, float bottom) const {
        return Intersects(fLeft, fTop, fRight, fBottom, left, top, right, bottom);
    }

    /**
     * @brief 检查矩形是否与另一个矩形相交
     * @param r 另一个矩形
     * @return 如果相交返回 true
     */
    /** Returns true if Rect intersects r.
        Returns false if either r or Rect is empty, or do not intersect.

        @param r  Rect to intersect
        @return   true if r and Rect have area in common
    */
    bool intersects(const Rect& r) const {
        return Intersects(fLeft, fTop, fRight, fBottom, r.fLeft, r.fTop, r.fRight, r.fBottom);
    }

    /**
     * @brief 静态方法：检查两个矩形是否相交
     * @param a 第一个矩形
     * @param b 第二个矩形
     * @return 如果相交返回 true
     */
    /** Returns true if a intersects b.
        Returns false if either a or b is empty, or do not intersect.

        @param a  Rect to intersect
        @param b  Rect to intersect
        @return   true if a and b have area in common
    */
    static bool Intersects(const Rect& a, const Rect& b) {
        return Intersects(a.fLeft, a.fTop, a.fRight, a.fBottom, b.fLeft, b.fTop, b.fRight, b.fBottom);
    }

    /**
     * @brief 与非空矩形取并集
     * @param r 要合并的矩形
     * 
     * 假设 r 非空。如果当前矩形为空，则直接赋值为 r。
     */
    /** Sets Rect to the union of itself and r.

        Asserts if r is empty and SK_DEBUG is defined.
        If Rect is empty, sets Rect to r.

        May produce incorrect results if r is empty.

        @param r  expansion Rect
    */
    void joinNonEmptyArg(const Rect& r) {
        MNN_ASSERT(!r.isEmpty());
        // if we are empty, just assign
        if (fLeft >= fRight || fTop >= fBottom) {
            *this = r;
        } else {
            this->joinPossiblyEmptyRect(r);
        }
    }

    /**
     * @brief 与可能为空的矩形取并集
     * @param r 要合并的矩形
     * 
     * 如果任一矩形为空，可能产生不正确的结果。
     */
    /** Sets Rect to the union of itself and the construction.

        May produce incorrect results if Rect or r is empty.

        @param r  expansion Rect
    */
    void joinPossiblyEmptyRect(const Rect& r) {
        fLeft   = std::min(fLeft, r.left());
        fTop    = std::min(fTop, r.top());
        fRight  = std::max(fRight, r.right());
        fBottom = std::max(fBottom, r.bottom());
    }

    /**
     * @brief 检查点是否在矩形内
     * @param x 点的 x 坐标
     * @param y 点的 y 坐标
     * @return 如果点在矩形内返回 true
     * 
     * 使用左闭右开区间 [left, right) 和 [top, bottom)。
     */
    /** Returns true if: fLeft <= x < fRight && fTop <= y < fBottom.
        Returns false if Rect is empty.

        @param x  test Point x-coordinate
        @param y  test Point y-coordinate
        @return   true if (x, y) is inside Rect
    */
    bool contains(float x, float y) const {
        return x >= fLeft && x < fRight && y >= fTop && y < fBottom;
    }

    /**
     * @brief 排序矩形
     * 
     * 如果 left > right，交换 left 和 right。
     * 如果 top > bottom，交换 top 和 bottom。
     * 结果矩形的宽度和高度将非负。
     */
    /** Swaps fLeft and fRight if fLeft is greater than fRight; and swaps
        fTop and fBottom if fTop is greater than fBottom. Result may be empty;
        and width() and height() will be zero or positive.
    */
    void sort() {
        using std::swap;
        if (fLeft > fRight) {
            swap(fLeft, fRight);
        }

        if (fTop > fBottom) {
            swap(fTop, fBottom);
        }
    }

    /**
     * @brief 创建排序后的矩形
     * @return 排序后的新矩形
     * 
     * 返回一个新矩形，其 left <= right 且 top <= bottom。
     */
    /** Returns Rect with fLeft and fRight swapped if fLeft is greater than fRight; and
        with fTop and fBottom swapped if fTop is greater than fBottom. Result may be empty;
        and width() and height() will be zero or positive.

        @return  sorted Rect
    */
    Rect makeSorted() const {
        return MakeLTRB(std::min(fLeft, fRight), std::min(fTop, fBottom), std::max(fLeft, fRight),
                        std::max(fTop, fBottom));
    }

    /**
     * @brief 获取指向第一个标量的指针
     * @return 指向 fLeft 的指针
     * 
     * 可以将矩形视为包含四个元素的数组。
     */
    /** Returns pointer to first scalar in Rect, to treat it as an array with four
        entries.

        @return  pointer to fLeft
    */
    const float* asScalars() const {
        return &fLeft;
    }
};

} // namespace CV
} // namespace MNN
#endif
